### ISSUE TITLE
Question on inputs to re-parameterization module

### ISSUE THREAD

**Issue by gitacct1800** [RenFeiTemp/SRN#2]
Hi, in the paper it is mentioned that the re-parameterization module takes the joint coordinates and the depth as inputs and outputs the 3D heat maps and unit vector fields. Do the joint coordinates here refer to the predicted joint coordinates from the previous regression module?

Thank you.

**Comment by RenFeiTemp** [comment]
Hi, your understanding is correct.

**Comment by gitacct1800** [comment]
Thanks for your reply.
