### ISSUE TITLE
Results for Hands2017 dataset

### ISSUE THREAD

**Issue by gitacct1800** [RenFeiTemp/SRN#4]
Thanks for sharing the realtime code. May I know how you obtained the seen and unseen results for the Hands2017 dataset? I'm looking the dataset but I'm not able to identify the subejct id of the train and test images.

**Comment by RenFeiTemp** [comment]
hi,@gitacct1800 ,you can submit the results to https://competitions.codalab.org/competitions/17356  to see the test results

**Comment by gitacct1800** [comment]
I see. Thank you!
