### ISSUE TITLE
provide training code

### ISSUE THREAD

**Issue by hetolin** [RenFeiTemp/SRN#5]
Hi, I am reading your paper and code recently. It is great work. Could you provide the training code? Thank you

**Comment by RenFeiTemp** [comment]
Hi! Sorry for the late reply. Because the code is ugly and I don't have time to clean it up recently, the training code of this project is not open source. If you don't mind, I can send you the relevant code for training through email.

**Comment by canuck6ix** [comment]
> Hi! Sorry for the late reply. Because the code is ugly and I don't have time to clean it up recently, the training code of this project is not open source. If you don't mind, I can send you the relevant code for training through email.

Could you also email it to me? thanks. (My handle at gmail dot com)

**Comment by PengfeiRen96** [comment]
Hi! We cleaned up the training code and opened it up. If you have any problems, please do not hesitate to ask us.
