### ISSUE TITLE
Are the predicted depths the pixel values of depth images or depth in millimetres?

### ISSUE THREAD

**Issue by vixrant** [RenFeiTemp/SRN#6]
Hi, I'm running the pertained model on DHG-14/24 and SHREC'17 hand datasets and its working perfectly. I was able to get the world coordinates in X and Y with an error of ~15mm in my dataset's world coordinate system.

However, I'm confused about the depth returned by SRN. In "Coordinate Decoupling" section of the paper, it's mentioned that SRN predicts scaled image coordinates and their corresponding depths in decoupled manner.  My question is, are these corresponding depths in pixel values as that of depth images, or are they in millimetres?

If I assume these are the depth image pixel values, I try to compare it to my dataset's depth values in world coordinate system (which is in meters), I get an average scaling factor of 0.00092, what I presume to be the depth scale of the RealSense camera used by my dataset's creators.

Multiplying SRN's output of depth by 0.00092 for px -> m conversion gives me a better estimation of depth than dividing by 1000 for mm -> m conversion when tested with my dataset's world depths. But if the returned depth values are in millimetres, I guess it's better to multiply by 0.001 to get meters directly to stay true to SRN's output format.

**Comment by RenFeiTemp** [comment]
Hi, sorry for the late reply. The depth value of the SRN output is consistent with the depth of the input normalized depth image. The normalized depth image is obtained by a cube with a fixed size. Therefore, if you want to get the depth value in the world coordinate system, you need to use the following equation: z_worldJoint = z_joint / 2 * cube_size + z_CubeCenter, where z_CubeCenter is the depth of the center of the cube in the world coordinate system. The unit of depth (mm/m) in the world coordinate system depends on the unit of the cube (mm/m).

**Comment by vixrant** [comment]
Thank you for the explanation. We were getting a mean absolute error of 45mm of SHREC '17 dataset due to our incorrect depth formula. This should help us.
