### ISSUE TITLE
Model size confusion

### ISSUE THREAD

**Issue by canuck6ix** [RenFeiTemp/SRN#7]
Hello and thanks for sharing your work.
According to Section 5.3 of your paper the model size is 21.3 MB. However, the checkpoint has a size of 128 MB. Is it a typo in the paper or am I missing something here? Thanks in advance.

**Comment by RenFeiTemp** [comment]
Hi, sorry for the late reply. The size of the model reported in our paper represents the parameters of the network, which we obtain through ptflops. The checkpoint stored by PyTorch contains many other parts, such as the parameters of the network optimizer.
