### ISSUE TITLE
Problem with custom dataset 

### ISSUE THREAD

**Issue by eliseeer** [RenFeiTemp/SRN#8]
Hello! I’m trying to use you’re NN with images acquired from my Kinect V2. 
I started in offline mode so simply acquiring some depth images from the Kinect, saving them in the *data/kinect2* folder and then running the *realtime.py* script.
However I wasn’t successful. This is an example of the results I get (I think the network it’s just guessing and drawing some random joints):
![8_1](https://user-images.githubusercontent.com/71637945/138439956-2350668f-c359-481c-980e-4a1dae0cb60f.png)

I digged more into the code to check if my images were different from yours and found that the depth was different, so I rescaled mine to be in the range of about 0-3000 and what I get is this: 
![Figure_1](https://user-images.githubusercontent.com/71637945/138440491-cc485e31-13db-4867-8e91-a11361fd7cdf.png)
instead of this (yours):
![Figure_1-1](https://user-images.githubusercontent.com/71637945/138440527-a3c5bdd6-7e33-4b5d-917e-0e1e663931e1.png)

Can you give me any suggestions please?
 
Moreover, I have some questions: 
- I don't understand how the center of the images is calculated in *get_center_adopt(img)*. Where does this 300 value come from? 
- Why do I get 3 output images from one input? 

Thanks in advance!

**Comment by PengfeiRen96** [comment]
Hi! This code can only detect the hand correctly when there is no object before it. Therefore, you need to keep your hands in front of all objects in the depth image.
300 is a default value to keep the code running when the hand can't be detected.
The three images are the original depth image, the cropped hand image, and the estimated hand pose.
